### ISSUE TITLE
Registering new users for email

### ISSUE THREAD

**Issue by daviesr** [foundersandcoders/How-Am-I-Doing#113]
Have recruited a young person to use the ocd questionnaire.  We did not set up an email for him, but used my work email,already registered, as the clinician contact address. (roger.davies@elft.nhs.uk).  Sharing failed.  We tried several,times over about 30 minutes after registration.  The user name is maqueen.

**Comment by eliascodes** [comment]
@daviesr I logged in to my account, changed the clinician e-mail to roger.davies@elft.nhs.uk and tried to send one of my questionnaire results to you. It seemed to work, you should hopefully receive an email digest soon.

I notice that the user "MAqueen" has typed in your e-mail with a capital 'R' and capital 'D'. That might be the source of the issue?

When you try to share, does the button text change to "Sent" or "Failed"?

**Comment by daviesr** [comment]
Thanks Elias,

We got failed repeatedly.  email is not usually case sensitive.  I'll text the young man and ask him to edit his account details and see if that makes a difference.  Will let you know if that makes a difference if he lets me know!

**Comment by daviesr** [comment]
Hi all,  I spoke to my volunteer user maqueen.  Changing the case of the email address had not worked.  However he had not registered an email address for himself.  We used the same address as for the clinician.  We were then able to share the results with my work email address.  Does the user email need to be completed?  Does the user email address also need to be registered with you?  The former is fine either way.  It would be easier (for clinicians and you) if the user email did not need to be registered.

**Comment by eliasmalik** [comment]
Hi Roger, yes thank you for working that out. Isabelle from Hillingdon was
also having the same issue. The user email does not need to be registered
with the service as far as I can see, but it does need to be a valid email
address. I will add some advice to the readme on github so that Mark knows
about it.

**Comment by daviesr** [comment]
Thanks.  I've asked for a central inbox to be set up in City and Hackney to receive shared forms.  The clinician coding now appears in the subject line in a way that will be helpful for distribution.  As soon as I know the inbox address I'll let you know.  Tower Hamlets are looking to do the same.  Lots of enthusiasm to try it out and much appreciation for all your work from all to whom I've shown it.

**Comment by daviesr** [comment]
Hi @eliascodes .  Tower Hamlets have beaten us to getting an email (our staff member is ill.  Please can you register THRCADS@elft.nhs.uk to receive emails forom the app.

Thanks

Roger

**Comment by eliasmalik** [comment]
@daviesr Invite has been sent

**Comment by daviesr** [comment]
Thanks @eliascodes.  Does the inbox manager need to do anything, ow will this now be live?

**Comment by eliasmalik** [comment]
The inbox manager needs to confirm that they agree to receiving e-mails. They will receive an e-mail shortly (if not already). There's just a button they need to click.
