### ISSUE TITLE
Clinician identifier

### ISSUE THREAD

**Issue by daviesr** [foundersandcoders/How-Am-I-Doing#117]
Is the clinician number an integer variable or a string, and if the latter, can a name or email address be used?

**Comment by eliasmalik** [comment]
@daviesr Currently the clinician number is required to be an alphanumeric string. Reasonably straightforward to change if you would like to allow email addresses though.

**Comment by daviesr** [comment]
Leave it for the moment.  I’ll set it up with using numbers and check with the admin team if this works for them.

Roger
