### ISSUE TITLE
Postgres issues

### ISSUE THREAD

**Issue by CYPIAPT-admin** [foundersandcoders/How-Am-I-Doing#120]
Hi @eliascodes Both myself and a service are having issues start a postgres server as part of the set up for cloning the project. I've ran initdb, but whenever I try and run the server and check status, it is not running. Do you have any guidance?

Mark

**Comment by eliasmalik** [comment]
I'll need a bit more information. Which server are you trying (and unable) to run, the postgres server or the HowAmIDoing server?

Are you getting any specific errors or messages in the terminal? Have you looked at your postgres logs? What do they say?

**Comment by CYPIAPT-admin** [comment]
Both, but I'm assuming that the later problem is caused by the first. 

For postgress, no errors in the terminal, and when I've set a log it doesn't exist when trying to open it. 

For the HAID server, I'm getting 

`Marks-MacBook-Air:how-am-i-doing markhemsley$ npm run db:migrate

> how-am-i-doing@1.0.0 db:migrate /Users/markhemsley/Documents/hackathon1/How-Am-I-Doing
> node ./assets/js/db/migrate.js

/Users/markhemsley/Documents/hackathon1/How-Am-I-Doing/node_modules/caminte/lib/schema.js:127
            throw new Error('Adapter ' + name + ' is not defined, try\n  npm install ' + name);
            ^

Error: Adapter  is not defined, try
  npm install 
    at new Schema (/Users/markhemsley/Documents/hackathon1/How-Am-I-Doing/node_modules/caminte/lib/schema.js:127:19)
    at module.exports (/Users/markhemsley/Documents/hackathon1/How-Am-I-Doing/server/db/schema.js:25:18)
    at Object.<anonymous> (/Users/markhemsley/Documents/hackathon1/How-Am-I-Doing/assets/js/db/migrate.js:9:55)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)

npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/Cellar/node/6.7.0/bin/node" "/usr/local/bin/npm" "run" "db:migrate"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.7
npm ERR! code ELIFECYCLE
npm ERR! how-am-i-doing@1.0.0 db:migrate: `node ./assets/js/db/migrate.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the how-am-i-doing@1.0.0 db:migrate script 'node ./assets/js/db/migrate.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the how-am-i-doing package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./assets/js/db/migrate.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs how-am-i-doing
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls how-am-i-doing
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/markhemsley/Documents/hackathon1/How-Am-I-Doing/npm-debug.log`

and in the 
[npm-debug.log.zip](https://github.com/foundersandcoders/How-Am-I-Doing/files/519422/npm-debug.log.zip)

**Comment by eliasmalik** [comment]
What environment variables are you running? You need the following:

```
JWT_KEY=this can be any random string
NODE_ENV=development or testing or production
DOMAIN=localhost
DB_DRIVER=postgres
DATABASE_URL=this should be your database connection URL
MAILGUN_API_KEY=You only need the mailgun credentials if you want the e-mail feature to work
MAILGUN_DOMAIN=As above
```

In particular, I suspect you're missing `DB_DRIVER`

**Comment by MHemsley** [comment]
All sorted now. Will add process to wiki.

@eliascodes could you make @CYPIAPT-admin, as I and others will be contributing to this in the near future, and thus you'll see issue not aimed at you guys but general dev going forward
